# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 32ff11bf08e1788f43f4660fb00225da0da08f4b6c57646c7a7d3e12549a9c89712b2b974626a3e32202dd0ecc8fd13093df28e9e4c8d7723137b75648f07861

test:
  secret_key_base: e27cc161fce77d9d722397769d8330cf151e23ef03327c0f8be48153b94262cf381687b5eb653da87075d8077d9d241772a36a530ae26a6473c77ecb2f52f291

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
